<?php
/**
 * X402 protocol helper that orchestrates payment requirements and verification.
 *
 * @package X402_Paywall
 */

// Exit if accessed directly.
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Protocol helper singleton.
 */
class X402_Paywall_Protocol {

    /**
     * Singleton instance.
     *
     * @var X402_Paywall_Protocol|null
     */
    private static $instance = null;

    /**
     * Protocol version tracked by the plugin.
     *
     * @var string
     */
    private $protocol_version = '1.0';

    /**
     * Payment handler wrapper.
     *
     * @var X402_Paywall_Payment_Handler
     */
    private $payment_handler;

    /**
     * Retrieve singleton instance.
     *
     * @return X402_Paywall_Protocol
     */
    public static function get_instance() {
        if (null === self::$instance) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Constructor.
     */
    private function __construct() {
        $this->payment_handler = new X402_Paywall_Payment_Handler();
    }

    /**
     * Retrieve protocol version.
     *
     * @return string
     */
    public function get_protocol_version() {
        return $this->protocol_version;
    }

    /**
     * Create payment requirements for a post.
     *
     * @param int   $post_id Post identifier.
     * @param array $config  Paywall configuration.
     *
     * @return object|null
     */
    public function create_payment_requirements($post_id, $config) {
        $requirements = $this->payment_handler->create_payment_requirements($post_id, $config);

        if ($requirements) {
            /**
             * Filter the generated payment requirements before returning them.
             *
             * @param object $requirements Requirements generated by the protocol handler.
             * @param int    $post_id      Post identifier.
             */
            $requirements = apply_filters('x402_payment_requirements', $requirements, $post_id);
        }

        return $requirements;
    }

    /**
     * Process a payment verification request.
     *
     * @param object $requirements Payment requirements.
     *
     * @return array
     */
    public function process_payment($requirements) {
        $result = $this->payment_handler->process_payment($requirements);

        /**
         * Filter the payment verification result before returning it.
         *
         * @param array $result Verification result array.
         */
        return apply_filters('x402_payment_verification_result', $result, $requirements);
    }

    /**
     * Get underlying payment handler.
     *
     * @return X402_Paywall_Payment_Handler
     */
    public function get_payment_handler() {
        return $this->payment_handler;
    }
}
